source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
# cocoapods-spm resolves the WhiskrKit Swift package for the WhiskrkitReactNative
# pod (see ios/Podfile). Needs CocoaPods >= 1.16 for its SPM support.
gem 'cocoapods', '>= 1.16'
gem 'cocoapods-spm'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
# xcodeproj's < 1.26 pin from the RN template is dropped: CocoaPods 1.16+
# (needed for cocoapods-spm's SPM support) requires xcodeproj >= 1.26.
gem 'concurrent-ruby', '< 1.3.4'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
