# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# WhiskrKit requires iOS 17.
platform :ios, '17.0'
prepare_react_native_project!

# Resolves the WhiskrKit Swift package for the WhiskrkitReactNative pod.
plugin 'cocoapods-spm'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'WhiskrkitExample' do
  # The WhiskrKit Swift package. 0.1.9 is the first release carrying the UIKit
  # attach(to:) API this wrapper needs.
  spm_pkg "WhiskrKit",
          :url => "https://github.com/whiskrkit/whiskrkit-swift.git",
          :version => "0.1.9"

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
